# Generated by Django 5.0.3 on 2024-03-25 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='foto-aluno/')),
                ('sexo', models.CharField(max_length=1)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.IntegerField()),
                ('cpf', models.IntegerField()),
            ],
        ),
    ]
